In [1]:
import pandas as pd
import sqlite3

with sqlite3.connect("../src/config/database.db") as conn:
    df = pd.read_sql_query("SELECT * FROM course_recommendation LIMIT 10", conn)
    display(df)

,title,link,institution,subject,level,prerequisites,language,videotranscript,associatedprograms,associatedskills
0,How to Learn Online,https://www.edx.org/learn/how-to-learn/edx-how...,edX,Education & Teacher Training,Introductory,NaN,English,English,NaN,Learning Design
1,The Science of Happiness,https://www.edx.org/learn/happiness/university...,"University of California, Berkeley",Social Sciences,Introductory,None.,English,English,NaN,"Evolutionary Biology, Empathy, Psychology"
2,Remote Work Revolutionfor Everyone,https://www.edx.org/learn/remote-work/harvard-...,Harvard University,Business & Management,Introductory,NaN,English,NaN,Professional Certificate inLeading in a Remote...,"Customer Relationship Building, Telecommuting"
3,CS50's Introduction toComputer Science,https://www.edx.org/learn/computer-science/har...,Harvard University,Computer Science,Introductory,None.,English,English,Professional Certificate inComputer Science fo...,"Resource Management, JavaScript (Programming L..."
4,Data Visualization andBuilding Dashboards with...,https://www.edx.org/learn/data-visualization/i...,IBM,Data Analysis & Statistics,Introductory,NaN,English,NaN,Professional CertificateinData Analysis and Vi...,"Data Visualization, Data Analysis, IBM Cognos ..."
5,"Six Sigma Part 2: Analyze,Improve, Control",https://www.edx.org/learn/six-sigma/technische...,Technische Universität München,Business & Management,Introductory,This course reviews basic statistics used in S...,English,English,Professional Certificate inLean Six Sigma Yell...,"Lean Manufacturing, Eight Disciplines Problem ..."
6,CS50's Introduction toProgramming with Python,https://www.edx.org/learn/python/harvard-unive...,Harvard University,Computer Science,Introductory,NaN,English,English,Professional Certificate inComputer Science fo...,"Computer Science, JavaScript (Programming Lang..."
7,Analyzing Data with Excel,https://www.edx.org/learn/excel/ibm-analyzing-...,IBM,Data Analysis & Statistics,Introductory,NaN,English,NaN,Professional CertificateinData Analysis and Vi...,"Spreadsheets, Data Cleansing, Microsoft Excel,..."
8,The Science of Generosity:Do Good…Feel Good,https://www.edx.org/learn/humanities/universit...,University of Pennsylvania,Philanthropy,Introductory,There are no prerequisites for this course.,English,English,NaN,NaN
9,EntrepreneurialOperations: Launching aStartup,https://www.edx.org/learn/entrepreneurship/bab...,Babson College,Business & Management,Intermediate,NaN,English,English,Professional Certificate inEntrepreneurial Min...,Operations

In [10]:
import sys
from pathlib import Path
import pandas as pd

sys.path.insert(0, str(Path("../src").resolve()))

from api.mock_api import MockJobAPI

db_path = str(Path("../src/config/database.db").resolve())
api = MockJobAPI(db_path=db_path)
job_postings_response = api.get_job_postings()

data = [
    {
        "title": job.title,
        "skills": ", ".join(job.associated_skills),
        "num_skills": len(job.associated_skills)
    }
    for job in job_postings_response.job_postings
]

df = pd.DataFrame(data)
display(df)

,title,skills,num_skills
0,How to Learn Online,Learning Design,1
1,The Science of Happiness,"Evolutionary Biology, Empathy, Psychology",3
2,Remote Work Revolutionfor Everyone,"Customer Relationship Building, Telecommuting",2
3,CS50's Introduction toComputer Science,"Resource Management, JavaScript (Programming L...",14
4,Data Visualization andBuilding Dashboards with...,"Data Visualization, Data Analysis, IBM Cognos ...",5
...,...,...,...
811,Logística Ecommerce yUltima milla,"Operations, Warehousing, Sales",3
812,New Space Economy,"Innovation, Broadcasting, Space Exploration, B...",11
813,Lifestyle MedicineFundamentals,"Oxidative Stress, Chronic Diseases, Epigenetics",3
814,Circular Economy: AnInterdisciplinary Approach,"Linear Model, Life Cycle Assessment, Emerging ...",10
815,Doing Gender and Why itMatters,"Resilience, Psychology, Sociology, Education P...",6